# This workflow will build a Java project with Gradle
# For more information see: https://docs.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        uses: AutoModality/action-clean@v1.1.0

      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          check-latest: true

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: "proxy/build/libs/velocity-proxy-*-all.jar"
          if-no-files-found: error
